server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test2
    username: postgres
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: mab.2000000@gmail.com
    password: tlqjngdsbtylkxrf

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


application:
  security:
    jwt:
      secret-key: ======================BezKoder=Spring============================================================
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days